version: "3.3"

services:
  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    ports:
      - "5175:5175"
  backend:
    build:
      context: ../go-backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_MODE=1
    ports:
      - "8084:8084"